name: "CD (Entrega/Delivery Continua): Main Workflow"

on:
  push:
    branches: [master, docker]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: | 
          npm install
          npm run build