name: "CI (Integração Continua): Main Workflow"

on:
  push:
    branches: [master, docker]
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Installation
        run: npm install
      - name: Run Linter
        run: npm run lint
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Installation
        run: npm install
      - name: Run Preview Deployment
        run: npm run deploy:preview
  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
      - name: Run Installation
        run: npm install
      - name: Run Teste e2e
        run: npm run test:e2e